---

development:
  DB_FILENAME: db/local/dev.db
  API_KEY: <RapidAPI_API_KEY>
  SESSION_SECRET: <SESSION_SECRET>

test:
  DB_FILENAME: db/local/test.db
  API_KEY: <RapidAPI_API_KEY>
  SESSION_SECRET: <SESSION_SECRET>